import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'book_progress_provider.freezed.dart';
part 'book_progress_provider.g.dart';

@freezed
sealed class BookProgressState with _$BookProgressState {
  const factory BookProgressState({
    required String itemId,
    @Default(0.0) double progress, // 0.0 to 1.0
    @Default(0.0) double currentTime, // in seconds
    @Default(0.0) double duration, // in seconds
    @Default(false) bool isFinished,
    @Default(false) bool isPlaying,
  }) = _BookProgressState;
}

@riverpod
class BookProgressNotifier extends _$BookProgressNotifier {
  @override
  BookProgressState? build() => null;

  void updateProgress({
    required String itemId,
    double? progress,
    double? currentTime,
    double? duration,
    bool? isFinished,
    bool? isPlaying,
  }) {
    if (state?.itemId == itemId) {
      // Update existing state
      state = state!.copyWith(
        progress: progress ?? state!.progress,
        currentTime: currentTime ?? state!.currentTime,
        duration: duration ?? state!.duration,
        isFinished: isFinished ?? state!.isFinished,
        isPlaying: isPlaying ?? state!.isPlaying,
      );
    } else {
      // Create new state
      state = BookProgressState(
        itemId: itemId,
        progress: progress ?? 0.0,
        currentTime: currentTime ?? 0.0,
        duration: duration ?? 0.0,
        isFinished: isFinished ?? false,
        isPlaying: isPlaying ?? false,
      );
    }
  }

  void clearProgress() {
    state = null;
  }
}

// Provider is now generated by @riverpod annotation above
