import 'dart:typed_data';
import 'package:audiobookshelf_flutter/model/libraries/detailed_library_item.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'selected_book_provider.freezed.dart';
part 'selected_book_provider.g.dart';

@freezed
sealed class SelectedBookState with _$SelectedBookState {
  const factory SelectedBookState({
    DetailedLibraryItem? book,
    Uint8List? coverImageBytes,
  }) = _SelectedBookState;
}

@riverpod
class SelectedBookNotifier extends _$SelectedBookNotifier {
  @override
  SelectedBookState build() => const SelectedBookState();

  void selectBook(DetailedLibraryItem book, {Uint8List? coverImageBytes}) {
    state = SelectedBookState(book: book, coverImageBytes: coverImageBytes);
  }

  void updateCoverImage(Uint8List coverImageBytes) {
    state = state.copyWith(coverImageBytes: coverImageBytes);
  }

  void clearSelection() {
    state = const SelectedBookState();
  }
}

// Provider is now generated by @riverpod annotation above
